spring:
  datasource:
    url: jdbc:mysql://123.207.25.93:3306/icpc_dev?serverTimezone=CTT&useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true
    username: root
    password: Shuicpc!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    #host: 47.100.89.70
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 2000
  mail:
    host: smtp.163.com
    username: 13120716616@163.com
    password: Lixiuwen24
    default-encoding: UTF-8

mail:
  fromMail:
    addr: 13120716616@163.com

thymeleaf:
  cache: false

server:
  port: 10010

mybatis:
  configuration:
    map-underscore-to-camel-case: true          #驼峰
  mapper-locations:  classpath:mapper/*.xml     #mapper xml
  type-aliases-package: com.shu.icpc.entity     #实体类包

