spring:
  datasource:
    url: jdbc:mysql://47.100.89.70:3306/icpc?serverTimezone=CTT&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    #host: 47.100.89.70
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 2000
  mail:
    host: smtp.163.com
    username: 13120716616@163.com
    password: Lixiuwen24
    default-encoding: UTF-8

mail:
  fromMail:
    addr: 13120716616@163.com

thymeleaf:
  cache: false

server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true          #驼峰
  mapper-locations:  classpath:mapper/*.xml     #mapper xml
  type-aliases-package: com.shu.icpc.entity     #实体类包




#code信息
code:
  common:
    success: 100
    illegal-data: 1001
    empty-validation: 1002
    unknown-error: 1003

  login:
    success-stu: 100
    success-coach: 101
    success-chief-coach: 102
    fail-checked: 103
    fail-rejected: 104
    fail-no-account: 105
    fail-wrong-password: 106
  sign-up:
    success: 100
    fail-account-exists: 101

